<?php $_config_vars = array (
  '_wr' => '/',
  '_img' => 'public/img/',
  '_FRSEL' => 'selected="selected"',
  '_FRCHK' => 'checked="checked"',
  '_CLASSACT' => 'class="actiu"',
  '_CLASSACTIVA' => 'class="activa"',
  '_TARGETBLANK' => ' onclick="window.open(this.href);return false;"',
  'OPT_MENU_PROYECTOS' => '0',
  'OPT_MENU_GABINETE' => '0',
  'OPT_MENU_CGA' => '0',
  'OPT_MENU2_PAGS' => '0',
  'OPT_MENU2_CONTROLLERS' => '0',
  'OPT_SUBMENU' => '0',
  'T_BOX' => '0',
  'JS_CAL' => '0',
  'TINY_MODE' => '0',
  'UNLOAD_CHK' => '0',
  'OPT_PARENT' => '0',
  'OPT_PAG_CONTS' => '0',
  'URL_BLOG' => 'http://www.sdfsdfsdf.com',
  'ID_ANALYTICS' => 'XXXXxxxxXXXX',
  'WWW_ANALYTICS' => '.dsfsfdsfs.com',
  'NOM_TWITTER' => '',
); ?>